# Generated by Django 4.1.3 on 2022-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('desctirtion', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='main/images/', verbose_name='Изоборажение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылки')),
            ],
        ),
    ]
